C_OUT = "./stackviz"

RUN_SCRIPT = "gdb -x {0} {1}"
C_COMPILE_ARGS = ["gcc", "-g", "ARG1", "-o", "ARG2"]
C_COMPILE = "gcc -g {0} -o {1}"

ARG1 = "ARG1"
ARG2 = "ARG2"

ASSEMBLY_START = "=>"
UNINITIALIZED = "null"

DISAS_IFILE = "./../gdb/disassemble.gdb"
DISAS_OFILE = "./../txt/disassemble.txt"
SCRIPT_FILE = "./../gdb/script.gdb"
INIT_FILE = "./../gdb/init.gdb"
LOG_FILE = "./../txt/log.txt"
FUNCTION_FILE = "./../gdb/function.gdb"

NOT_C_SOURCE = "ERROR: not a C source file"
TITLE = "StackViz"
ARROW_ICON = "./../static/arrow.png"
STACK_ICON = "./../static/stack.png"

BASH_PROMPT = "\$"
GDB_PROMPT = "\(gdb\)"
OUTPUT_REDIRECT = "Redirecting output to {0}"
DONE_LOGGING = "Done logging to {0}"
GDB_INIT_CMD = "gdb -x {0} {1}"
REMOVE_BR = "clear"
RUN = "run"
CONTINUE = "continue"
LINE_STEP = "step"
FUNCTION_STEP = "finish"
SOURCE = "source {0}"
SET_LOG_FILE = "set logging file {0}"
SET_LOG_ON = "set logging on"
SET_LOG_OFF = "set logging off"
VAL_AT_ADDR = "x/{0}x {1}"
INFO_SCOPE = "info scope {0}"
SRC_LINE = "info line"
INFO_FRAME = "info frame"
INFO_ARGS = "info locals"
REG_VAL = "x/x ${0}"
TRACE_ON = "set trace-commands on"
TRACE_OFF = "set trace-commands off"
PRINT_SYMBOL = "print {0}"
PRINT_REGISTER = "print ${0}"

BASE_POINTER = "rbp"
STACK_POINTER = "rsp"
BASE_POINTERS = ["rbp", "ebp"]
STACK_POINTERS = ["rip", "eip"]

VAR_REGEX = "^([a-zA-Z0-9_-]*)\s=\s"
PTR_REGEX = "([0-9a-zA-Z]+):\s.*"
ADDR_REGEX = "[0-9a-zA-Z]+:\s(.*)"
LEVEL_REGEX = ".*[.|\s]*Stack level ([0-9])+"
BOTTOM_REGEX = ".*[.|\s]*Stack level [0-9]+, frame at ([0-9a-zA-Z]*):"
FUNCTION_REGEX = ".*\s*rip\s*=.*in\s+([0-9a-zA-Z\_\-]+)"
LINE_REGEX = ".*\.c:([0-9]+)\);"
SAVED_REG_REGEX = ".*Saved registers:\s*(.*)"
REG_ADDR_REGEX = "([a-zA-Z]{3})\sat\s(0x[0-9a-zA-Z]*)"
SYMBOL_REGEX = ".*Symbol\s([0-9a-zA-Z_-]*).*offset\s0\+([-|0-9]*),\slength\s([0-9]*).$"
LINE_NUM_REGEX = "Line\s([0-9]*)"
PRINT_REGEX = "\$[0-9]*\s=\s(.*)"
PRINT_REGISTER_REGEX = "\$[0-9]*\s=\s\(void \*\)\s(.*)"
RETURN_REGEX = "Value\sreturned\sis\s\$[0-9]*\s=\s([0-9a-zA-Z]*)"
BREAKPOINT_REGEX = "Breakpoint [0-9]*,"
